### ISSUE TITLE
Miktex package is broken

### ISSUE THREAD

**Issue by ianhbell** [wspr/breqn#10]
I have tried for several hours to get the breqn package to work on miktex on windows.  Complete failure, and I always end up getting this error:

```
! LaTeX Error: File `breqn.sty' not found.
```

whenever I have `\usepackage{breqn}` in my preamble.  I have tried all manner of uninstall/reinstall permutations.

It would be great if this could be fixed.  My "solution" was to unpack the .dtx files into the directory that my file is in, which is clearly not a nice solution.

**Comment by wspr** [comment]
Unfortunately I have no idea how to debug MiKTeX problems. I assume that there’s no problem with the upload to CTAN, so it would be more appropriate to liaise with MiKTeX-specific support.
