### ISSUE TITLE
sort out ins/dtx

### ISSUE THREAD

**Issue by wspr** [wspr/breqn#23]
Currently the .ins files are generated files but they are also included in the ctan zip release. Should be one or the other.

With l3build being able to automate versioning and copyright we can now drop the self-extracting .dtx files (I think) and distribute the .ins files separately.

**Comment by josephwright** [comment]
I've wondered about copyright lines, and also Markdown (or similar) ChangeLogs. I think tat all fits into `l3build tag`, just have to write some model Lua code!

**Comment by wspr** [comment]
mostly sorted. need to add copyright updating but that's about it.
