### ISSUE TITLE
Problem with breqn and mathtools

### ISSUE THREAD

**Issue by Volker-Weissmann** [wspr/breqn#33]
The following code does not compile:
```
\documentclass{article}
\usepackage{breqn}
\usepackage{mathtools}
\begin{document}\end{document}
```

but the following code compiles just fine

```
\documentclass{article}
\usepackage{mathtools}
\usepackage{breqn}
\begin{document}\end{document}
```

It would be a nice improvement, if you could either make sure that the first version also compiles or outputs an error message that says that you should switch the order of the usepackages.

**Comment by FrankMittelbach** [comment]
see also https://github.com/latex3/latex2e/issues/209 (closed there)

**Comment by wspr** [comment]
Ah, this isn't anything to do with mathtools; here is a further reduced minimal example:

\documentclass{article}
\usepackage{breqn}
\AtBeginDocument{\RequirePackage{graphicx}}
\begin{document}\end{document}

I guess I could fix this just by loading graphicx inside of breqn!
