### ISSUE TITLE
loading order w/ etoolbox

### ISSUE THREAD

**Issue by jspitz** [wspr/breqn#34]
This is just a minor (supposedly documentation) issue. If `etoolbox` (or a package that loads it, such as `polyglossia`) is loaded after `breqn`, the following warning is issued:
```
Package etoolbox Warning: Patching '\end' failed!
(etoolbox)                '\AfterEndEnvironment' will not work.
```

MWE:
```tex
\documentclass{minimal}
%\usepackage{etoolbox}
\usepackage{breqn}
\usepackage{etoolbox}
\begin{document}
Hi.
\end{document}
```

**Comment by wspr** [comment]
Thanks. This makes me wonder whether breqn should use etoolbox for the patching that it does. Would kill two birds with one stone — simpler code, and less conflict…

**Comment by jspitz** [comment]
No longer reproducable. Possible resolved in the wake of the new LaTeX hook implementation?
