### ISSUE TITLE
comflict between breqn and flexisym

### ISSUE THREAD

**Issue by jszhao** [wspr/breqn#37]
The following two pieces of code will give errors:
```
\documentclass{article}
\usepackage[cmbase]{flexisym}
\usepackage{breqn}
\begin{document}
\end{document}
```
and 
```
\documentclass{article}
\usepackage{breqn}
\usepackage[cmbase]{flexisym}
\begin{document}
\end{document}
```
The first piece of code worked before the last (I am not very sure about it) update (2020/02/16 0.98h). After remove `[cmbase]`, the second piece of code works.

Any hint?

**Comment by josephwright** [comment]
`breqn` requires `flexisym` so you have to load the latter first.

**Comment by jszhao** [comment]
> 
> 
> `breqn` requires `flexisym` so you have to load the latter first.

then the code
```
\documentclass{article}
\usepackage{flexisym}
\usepackage{breqn}
\begin{document}
\end{document}
```
give the following error message:
```
! LaTeX Error: Command \dfrac already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.228 \newcommand{\dfrac}{\genfrac{}{}{}0}
```
Any hint? Thanks a lot.

**Comment by jszhao** [comment]
The above error stems from that `mathstyle` package is loaded before `amsmath` package.

In the document of `mathsytle` package, it said that `If you want to use this package with amsmath, it is important mathstyle is loaded after amsmath.`

In the above example, `amsmath` package is required by by `breqn` package, and `mathstyle` package is require by `flexisym` package. However, `flexisym` package should be load before `breqn` package, thus, that causes the `amsmath` package is loaded after `mathstyle` package.

How to fix it? Thanks a lot.

**Comment by jszhao** [comment]
well, the solution to this error is to load the `amsmath` package explicitly before the `flexisym` package, as following, 
```
\documentclass{standalone}
\usepackage{amsmath}
\usepackage[cmbase]{flexisym}
\usepackage{breqn}
\begin{document}
\end{document}
```

**Comment by wspr** [comment]
Thanks for this discussion, I’ve updated the docs to make this more clear.
