### ISSUE TITLE
TexLive 2014 version doesn't include cmbase.sym

### ISSUE THREAD

**Issue by jpallen** [wspr/breqn#4]
Apologies if this is actually an upstream TeXLive 2014 issue, but breqn seems broken in TeXLive 2014 currently. It seems that only breqn.sty, flexisym.sty and mathstyle.sty are included, but additional files like cmbase.sym are missing. I note that if I run `tex flexistm.dtx` then these are generated correctly, but `latex flexistm.dtx` does not generate them. The cmbase.sym file is also missing in the breqn.tds.zip /source directory on CTAN (will this be where TeXLive gets it from?)

The missing cmbase.sym file causes the following error: "LaTeX Error: File 'cmbase.sym' not found." when calling `\usepackage{breqn}`

**Comment by ziadziad6** [comment]
Hi all, sorry for my question but I am really a beginner, could you please guys tell me where to run this code 

$ cd /usr/local/texlive/2014/texmf-dist/tex/latex/breqn
$ sudo tex breqn.dtx
$ sudo tex flexisym.dtx
$ sudo tex mathstyle.dtx
$ sudo mktexlsr

as I installed TexLive 2014 but still have the same problem

Regards

**Comment by wspr** [comment]
@ziadziad6 — You shouldn't need to run this code; the version of `breqn` on CTAN has fixed this issue. If necessary, you can download the `.tds.zip` file from <https://www.ctan.org/pkg/breqn>, but simply updating TeXLive using `tlmgr` should be all you need.

**Comment by ziadziad6** [comment]
Thank you very much @wspr  for your response
